spring.application.name=medical-intern-system

# ===============================
# SERVER (CRITICAL FIX)
# ===============================
server.port=${PORT}
server.address=0.0.0.0

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.main.lazy-initialization=true
spring.jpa.defer-datasource-initialization=true

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.mims=DEBUG

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=300000

# ===============================
# CAPTCHA
# ===============================
captcha.enabled=false

# ===============================
# DEVTOOLS
# ===============================
spring.devtools.restart.enabled=false
spring.main.banner-mode=console

server.tomcat.connection-timeout=5s


spring.datasource.hikari.initialization-fail-timeout=0

server.tomcat.accept-count=100
server.tomcat.max-connections=200